# Generated by Django 3.2 on 2022-03-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_url', models.URLField(max_length=100, unique=True)),
                ('token', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('client_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
